/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'accountManagement', { get: function () { return require('./account-management'); } });
Object.defineProperty(exports, 'alertChannel', { get: function () { return require('./alert-channel'); } });
Object.defineProperty(exports, 'alertCondition', { get: function () { return require('./alert-condition'); } });
Object.defineProperty(exports, 'alertMutingRule', { get: function () { return require('./alert-muting-rule'); } });
Object.defineProperty(exports, 'alertPolicy', { get: function () { return require('./alert-policy'); } });
Object.defineProperty(exports, 'alertPolicyChannel', { get: function () { return require('./alert-policy-channel'); } });
Object.defineProperty(exports, 'apiAccessKey', { get: function () { return require('./api-access-key'); } });
Object.defineProperty(exports, 'applicationSettings', { get: function () { return require('./application-settings'); } });
Object.defineProperty(exports, 'browserApplication', { get: function () { return require('./browser-application'); } });
Object.defineProperty(exports, 'cloudAwsGovcloudIntegrations', { get: function () { return require('./cloud-aws-govcloud-integrations'); } });
Object.defineProperty(exports, 'cloudAwsGovcloudLinkAccount', { get: function () { return require('./cloud-aws-govcloud-link-account'); } });
Object.defineProperty(exports, 'cloudAwsIntegrations', { get: function () { return require('./cloud-aws-integrations'); } });
Object.defineProperty(exports, 'cloudAwsLinkAccount', { get: function () { return require('./cloud-aws-link-account'); } });
Object.defineProperty(exports, 'cloudAzureIntegrations', { get: function () { return require('./cloud-azure-integrations'); } });
Object.defineProperty(exports, 'cloudAzureLinkAccount', { get: function () { return require('./cloud-azure-link-account'); } });
Object.defineProperty(exports, 'cloudGcpIntegrations', { get: function () { return require('./cloud-gcp-integrations'); } });
Object.defineProperty(exports, 'cloudGcpLinkAccount', { get: function () { return require('./cloud-gcp-link-account'); } });
Object.defineProperty(exports, 'cloudOciLinkAccount', { get: function () { return require('./cloud-oci-link-account'); } });
Object.defineProperty(exports, 'dataPartitionRule', { get: function () { return require('./data-partition-rule'); } });
Object.defineProperty(exports, 'entityTags', { get: function () { return require('./entity-tags'); } });
Object.defineProperty(exports, 'eventsToMetricsRule', { get: function () { return require('./events-to-metrics-rule'); } });
Object.defineProperty(exports, 'group', { get: function () { return require('./group'); } });
Object.defineProperty(exports, 'infraAlertCondition', { get: function () { return require('./infra-alert-condition'); } });
Object.defineProperty(exports, 'insightsEvent', { get: function () { return require('./insights-event'); } });
Object.defineProperty(exports, 'keyTransaction', { get: function () { return require('./key-transaction'); } });
Object.defineProperty(exports, 'logParsingRule', { get: function () { return require('./log-parsing-rule'); } });
Object.defineProperty(exports, 'monitorDowntime', { get: function () { return require('./monitor-downtime'); } });
Object.defineProperty(exports, 'notificationChannel', { get: function () { return require('./notification-channel'); } });
Object.defineProperty(exports, 'notificationDestination', { get: function () { return require('./notification-destination'); } });
Object.defineProperty(exports, 'nrqlAlertCondition', { get: function () { return require('./nrql-alert-condition'); } });
Object.defineProperty(exports, 'nrqlDropRule', { get: function () { return require('./nrql-drop-rule'); } });
Object.defineProperty(exports, 'obfuscationExpression', { get: function () { return require('./obfuscation-expression'); } });
Object.defineProperty(exports, 'obfuscationRule', { get: function () { return require('./obfuscation-rule'); } });
Object.defineProperty(exports, 'oneDashboard', { get: function () { return require('./one-dashboard'); } });
Object.defineProperty(exports, 'oneDashboardJson', { get: function () { return require('./one-dashboard-json'); } });
Object.defineProperty(exports, 'oneDashboardRaw', { get: function () { return require('./one-dashboard-raw'); } });
Object.defineProperty(exports, 'pipelineCloudRule', { get: function () { return require('./pipeline-cloud-rule'); } });
Object.defineProperty(exports, 'serviceLevel', { get: function () { return require('./service-level'); } });
Object.defineProperty(exports, 'syntheticsAlertCondition', { get: function () { return require('./synthetics-alert-condition'); } });
Object.defineProperty(exports, 'syntheticsBrokenLinksMonitor', { get: function () { return require('./synthetics-broken-links-monitor'); } });
Object.defineProperty(exports, 'syntheticsCertCheckMonitor', { get: function () { return require('./synthetics-cert-check-monitor'); } });
Object.defineProperty(exports, 'syntheticsMonitor', { get: function () { return require('./synthetics-monitor'); } });
Object.defineProperty(exports, 'syntheticsMultilocationAlertCondition', { get: function () { return require('./synthetics-multilocation-alert-condition'); } });
Object.defineProperty(exports, 'syntheticsPrivateLocation', { get: function () { return require('./synthetics-private-location'); } });
Object.defineProperty(exports, 'syntheticsScriptMonitor', { get: function () { return require('./synthetics-script-monitor'); } });
Object.defineProperty(exports, 'syntheticsSecureCredential', { get: function () { return require('./synthetics-secure-credential'); } });
Object.defineProperty(exports, 'syntheticsStepMonitor', { get: function () { return require('./synthetics-step-monitor'); } });
Object.defineProperty(exports, 'user', { get: function () { return require('./user'); } });
Object.defineProperty(exports, 'workflow', { get: function () { return require('./workflow'); } });
Object.defineProperty(exports, 'workload', { get: function () { return require('./workload'); } });
Object.defineProperty(exports, 'dataNewrelicAccount', { get: function () { return require('./data-newrelic-account'); } });
Object.defineProperty(exports, 'dataNewrelicAlertChannel', { get: function () { return require('./data-newrelic-alert-channel'); } });
Object.defineProperty(exports, 'dataNewrelicAlertPolicy', { get: function () { return require('./data-newrelic-alert-policy'); } });
Object.defineProperty(exports, 'dataNewrelicApplication', { get: function () { return require('./data-newrelic-application'); } });
Object.defineProperty(exports, 'dataNewrelicAuthenticationDomain', { get: function () { return require('./data-newrelic-authentication-domain'); } });
Object.defineProperty(exports, 'dataNewrelicCloudAccount', { get: function () { return require('./data-newrelic-cloud-account'); } });
Object.defineProperty(exports, 'dataNewrelicEntity', { get: function () { return require('./data-newrelic-entity'); } });
Object.defineProperty(exports, 'dataNewrelicGroup', { get: function () { return require('./data-newrelic-group'); } });
Object.defineProperty(exports, 'dataNewrelicKeyTransaction', { get: function () { return require('./data-newrelic-key-transaction'); } });
Object.defineProperty(exports, 'dataNewrelicNotificationDestination', { get: function () { return require('./data-newrelic-notification-destination'); } });
Object.defineProperty(exports, 'dataNewrelicObfuscationExpression', { get: function () { return require('./data-newrelic-obfuscation-expression'); } });
Object.defineProperty(exports, 'dataNewrelicServiceLevelAlertHelper', { get: function () { return require('./data-newrelic-service-level-alert-helper'); } });
Object.defineProperty(exports, 'dataNewrelicSyntheticsPrivateLocation', { get: function () { return require('./data-newrelic-synthetics-private-location'); } });
Object.defineProperty(exports, 'dataNewrelicSyntheticsSecureCredential', { get: function () { return require('./data-newrelic-synthetics-secure-credential'); } });
Object.defineProperty(exports, 'dataNewrelicTestGrokPattern', { get: function () { return require('./data-newrelic-test-grok-pattern'); } });
Object.defineProperty(exports, 'dataNewrelicUser', { get: function () { return require('./data-newrelic-user'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

